server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biomed_info_system?serverTimezone=UTC
    username: root
    password: ssy123
